### ISSUE TITLE
meta tags

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/website-static#2]
are all these present and correct, on each page:
- page title tags
-  page description tags
- social media stuff

**Comment by bensteinberg** [comment]
title in head is different:

```
<title>The Library Innovation Lab at Harvard University</title>
```

in production, and 

```
 <title>
  
    We're building things in libraries. | Library Innovation Lab
  
</title>
```

in the static site.

**Comment by rebeccacremona** [comment]
## home page 
<meta property='og:image' content='http://lil.law.harvard.edu/theme/lil/images/header-splash-logo-ani@1x.gif'/>
<meta content="Home of Perma.cc, H2O, Awesome Box, and others. We’re building things in libraries." name="description">

## about 
<meta property='og:image' content='http://lil.law.harvard.edu/thumbs/800x800r/2016-09/1474641879_langdell-narrow.jpg'/>
<meta content="Bringing the best of technology to the world of libraries and the best of libraries to the world of technology. And vice versa." name="description">

## projects
<meta property='og:image' content=''/>
<meta content="Our projects attempt to make something better, simpler, more transparent, or more fun." name="description">

## sketches
<meta content="Sketches are a way to get a handle on an idea and see where it goes." name="description">
<meta property='og:image' content=''/>

## fellows
<meta content="Bringing the best of technology to the world of libraries and the best of libraries to the world of technology. And vice versa." name="description">
<meta property='og:image' content='http://lil.law.harvard.edu/thumbs/800x800r/2016-09/langdell-narrow.jpg'/>

## jobs
<meta content="Bringing the best of technology to the world of libraries and the best of libraries to the world of technology. And vice versa." name="description">
<meta property='og:image' content='http://lil.law.harvard.edu/thumbs/800x800r/2016-09/1474641879_langdell-narrow.jpg'/>

## awesome box
<meta content="Awesome Box helps libraries tag and share the books their patrons love." name="description">
<meta property='og:image' content='http://lil.law.harvard.edu/thumbs/800x600r/2015-07/awesome-box-thumbnail-1.png'/>

## cap
<meta content="The Caselaw Access Project is making all U.S. case law freely accessible online." name="description">
<meta property='og:image' content='http://lil.law.harvard.edu/thumbs/800x600r/2015-07/free-the-law-thumbnail-0.png'/>

## h20
<meta content="H2O is a platform for creating, sharing and remixing open course materials." name="description">
<meta property='og:image' content='http://lil.law.harvard.edu/thumbs/800x600r/2015-07/h20-thumbnail-1.png'/>

etc.

**Comment by rebeccacremona** [comment]
66dc9fb8e0a831b2352d6d04228bf9ec191a2871
5a141dab40f6a0de4f6d6d77864fcfba74746be1
8ec7141affd95bca89cd666142fa03c5dc8dd8c5
