### ISSUE TITLE
custom footers

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/website-static#3]
Are all the right footers present?

**Comment by bensteinberg** [comment]
Footer icon is different in 
- /projects/haystacks
- /projects/h2o
- /projects/caselaw-access-project
- /projects/nuremberg-project
- /projects/perma-cc
- /projects/stack-life
- /projects/time-capsule-encryption

**Comment by bensteinberg** [comment]
Footer icon is present in the static site but not in production at 
- /sketches/canifairuse-it/
- /sketches/ftl-topic-mapping/
- /sketches/local-memory/
- /sketches/private-talking-spaces/
- /sketches/squarewave/

**Comment by rebeccacremona** [comment]
Thanks!

Added missing custom footers in https://github.com/harvard-lil/website-static/commit/50c7d14cf9114946286545879e7c6a56516d6a28

The missing logo in the footer of those sketches is, IMO a bug in the production site: there should be some default fallback. Presently using the home page logo here.
