### ISSUE TITLE
How to deploy?

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/website-static#32]
Rsync from local machine manually? Bash script that rsyncs from local machine? Rsync from inside the jekyll container? Other ideas?

**Comment by rebeccacremona** [comment]
Complicating factor: we don't have arbitrary write access to the public web directory on that server: ITS has to move files there. After they do, BRS should be able to update said files, but won't be able to upload new ones.... So, any time we have a new page, ITS has to get involved.

**Comment by bensteinberg** [comment]
I think we could now theoretically set up a key and rsync the build from Travis on push to master, but Travis would need to connect to the VPN, which isn't going to happen. I'm going to contemplate some kind of pull process.
