### ISSUE TITLE
stretchandy

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/website-static#48]
from the blog (I know ... it's WP), but:

![screen shot 2017-03-10 at 6 23 15 am](https://cloud.githubusercontent.com/assets/2140548/23793607/192d7696-055a-11e7-8162-0b54f2d19a9e.png)

**Comment by bensteinberg** [comment]
Ah, that must be a side-effect of my changing the link from HTTP to HTTPS. Sorry, will take a look.

**Comment by bensteinberg** [comment]
Fixed -- I changed both images from "original size" to "large".
