### ISSUE TITLE
Site does not mention me enough

### ISSUE THREAD

**Issue by jayed** [harvard-lil/website-static#7]
I feel that I am not displayed prominently enough. My personal brand could suffer from this lack of Jay-SEO-awareness.

Please fix. Thx.

**Comment by ChefAndy** [comment]
I'm going to rate this as Sev 1. Let's get everybody on a conference call until we're satisfied that this is under control.

On Jan 6, 2017, at 10:59 PM, Jay <notifications@github.com<mailto:notifications@github.com>> wrote:


I feel that I am not displayed prominently enough. My personal brand could suffer from this lack of Jay-SEO-awareness.

Please fix. Thx.

**Comment by rebeccacremona** [comment]
This ought to do it:

![seo](https://cloud.githubusercontent.com/assets/11020492/22115188/1132aaca-de3a-11e6-8e4c-4c393c85bf65.png)

**Comment by jayed** [comment]
Greatly appreciated.
