### ISSUE TITLE
typo in redirect

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/website-static#95]
brett_j [3:05 PM] 
hey, I noticed http://librarylab.law.harvard.edu/projects/free-the-law redirects to http://lil.law.harvard.edu/projects/case-law-access-project/ , but it should redirect to http://lil.law.harvard.edu/projects/caselaw-access-project/ ...who do you think I should nudge about that? or put it in as an issue in the LIL website github? (edited)

rcremona [3:08 PM] 
Aha! Nice catch!
That’s a typo here: https://github.com/harvard-lil/website-static/blob/develop/app/.htaccess#L46
We can change it and redeploy

**Comment by bensteinberg** [comment]
Closed in https://github.com/harvard-lil/website-static/pull/96 and deployed
